Flask_Blog/app/blog/models.py
from datetime import datetime
from enum import IntEnum
from RealProject import db
from sqlalchemy.dialects.mysql import LONGTEXT


class BaseModel(db.Model):
    """基类模型"""

    __abstract__ = True

    add_date = db.Column(db.DateTime, nullable=False, default=datetime.now)
    pub_date = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now, nullable=False)


class PostPublishType(IntEnum):
    """文章发布类型"""
    draft = 1   # 草稿
    show = 2    # 发布


class Category(BaseModel):
    """文章分类模型"""
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128), nullable=False)
    icon = db.Column(db.String(128), nullable=True)

    # 文章类别和文章的关系：一 对 多
    # db.relationship：写在“一”方，关联“多”方，“多”方可以通过 backref='category' 访问到其对应的“一”方的对象
    # post = db.relationship('Post', back_populates='category')
    post = db.relationship('Post', backref='category', lazy=True)

    def __repr__(self):
        return '<Category %r>' % self.name


# 文章和文章标签的关系：多 对 多
# 多对多关系帮助器表
tags = db.Table(
    'tags',
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'), primary_key=True),
    db.Column('post_id', db.Integer, db.ForeignKey('post.id'), primary_key=True)
)


class Post(BaseModel):
    """文章模型"""
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(128), nullable=False)
    desc = db.Column(db.String(200), nullable=True)
    content = db.Column(LONGTEXT, nullable=False)
    has_type = db.Column(db.Enum(PostPublishType), server_default='show', nullable=False)

    # db.ForeignKey：写在“多”方，关联“一”方的某一个属性
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'), nullable=False)

    # 多对多关系
    tags = db.relationship('Tag', secondary=tags, lazy='subquery', backref=db.backref('post', lazy=True))

    def __repr__(self):
        return '<Post %r>' % self.title


class Tag(BaseModel):
    """文章标签模型"""
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128), nullable=False, unique=True)

    def __repr__(self):
        return '<Tag %r>' % self.name

Flask_Blog/app/blog/views.py
import re
from sqlalchemy import and_, extract, or_
from flask import Blueprint, render_template, request

from .models import Post, Category, Tag


# 前两个为必填参数，蓝图名称和模块名称
# url_prefix='/blog' 指定了前缀路径
bp = Blueprint('blog', __name__, url_prefix='/blog', template_folder='templates', static_folder='static')


def index():
    """
    首页
    ---
    tags:
        - 首页接口
    description:
        - 显示站内信息
    responses:
        200:
            description: OK
            example: {'code': 1, 'message': OK}
    """
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(-Post.add_date).paginate(page=page, per_page=9, error_out=False)
    post_list = pagination.items

    import random
    imgs = ['https://gimg2.baidu.com/image_search/src=http%3A%2F%2Finews.gtimg.com%2Fnewsapp_bt%2F0%2F14297516724%2F641&refer=http%3A%2F%2Finews.gtimg.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1673502104&t=80b40881482c684b6b5cfd4570283d1c',
            'https://img2.baidu.com/it/u=2048195462,703560066&fm=253&fmt=auto&app=138&f=JPEG?w=500&h=333',
            'https://gimg2.baidu.com/image_search/src=http%3A%2F%2Flmg.jj20.com%2Fup%2Fallimg%2F1113%2F052420110515%2F200524110515-2-1200.jpg&refer=http%3A%2F%2Flmg.jj20.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1673502162&t=986f3242d469df7f19fe558a3dd19c29']

    for post in post_list:
        post.img = random.sample(imgs, 1)[0]
        # post.img = random.choice(imgs)
    return render_template('index.html', pagination=pagination, post_list=post_list)


@bp.route('/category/<int:cate_id>')
def cates(cate_id):
    """
    类别文章
    ---
    tags:
        - blog
    decription:
        - 显示属于该类别的文章文章列表
    parameters:
        - name: cate_id
          in: path
          description: 类别的id值
          required: true
          type: number
    responses:
        '200':
            description: 返回该类别的文章信息
            schema:
                type: string
        'default':
            description: Unexpected Error
    """
    cate = Category.query.get(cate_id)
    page = request.args.get('page', default=1, type=int)

    pagination = post_list = Post.query.filter(Post.category_id == cate_id).\
        paginate(page=page, per_page=10, error_out=False)
    post_list = pagination.items
    return render_template('cate_list.html', cate=cate, post_list=post_list, pagination=pagination, cate_id=cate_id)


@bp.route('/category/<int:cate_id>/<int:post_id>')
def detail(cate_id, post_id):
    """
    文章详情
    ---
    tags:
        - blog
    description:
        - 显示文章详情
    parameters:
        - name: cate_id
          in: path
          description: 类别id
          required: true
          type: number
        - name: post_id
          in: path
          description: 文章id
          required: true
          type: number
    responses:
        '200':
            description: 返回文章详情信息
        'default':
            description: Unexpected Error
    """
    cate = Category.query.get(cate_id)
    post = Post.query.get_or_404(post_id)

    # post.tags中保存的是Tag对象，在html中显示标签时会显示 <Tag 'tag1'> ，而不是 'tag1'
    # 所以通过传递一个包含 tag.name 的列表，在html显示正确的标签名
    tag_list = []
    for tag in post.tags:
        tag_list.append(tag.name)

    # 上一篇
    prev_post = Post.query.filter(Post.id < post_id).order_by(-Post.id).first()
    # 下一篇
    next_post = Post.query.filter(Post.id > post_id).order_by(Post.id).first()

    return render_template(
        'detail.html', cate=cate, post=post, prev_post=prev_post, next_post=next_post, tag_list=tag_list
    )


@bp.context_processor
def inject_archive():
    # 文章归档日期注入上下文
    posts = Post.query.order_by(-Post.add_date)
    dates = set([post.add_date.strftime("%Y年%m月") for post in posts])

    # 标签
    tags = Tag.query.all()
    for tag in tags:
        tag.style = ['is-success', 'is-danger', 'is-black', 'is-light', 'is-primary', 'is-link', 'is-info', 'is-warning']

    # 最新文章
    new_posts = posts.limit(2)

    return dict(dates=dates, tags=tags, new_posts=new_posts)


@bp.route('/category/<string:date>')
def archive(date):
    """
    时间内发布的文章列表
    ---
    tags:
        - blog
    description:
        - 时间内发布的文章列表
    parameters:
        - name: date
          in: path
          description: 要查询的时间，例：2022年12月
          required: true
          type: string
    responses:
        '200':
            description: 返回时间内发布的文章列表
        'default':
            description: Unexpected Error
    """
    regex = re.compile(r'\d{4}|\d{2}')
    dates = regex.findall(date)

    page = request.args.get('page', 1, type=int)

    # 根据年月获取数据
    archive_posts = Post.query.filter(
        and_(
            extract('year', Post.add_date) == int(dates[0]),
            extract('month', Post.add_date) == int(dates[1])
        )
    )

    pagination = archive_posts.paginate(page=page, per_page=10, error_out=False)
    post_list = pagination.items

    return render_template('archive.html', post_list=post_list, pagination=pagination, date=date)


@bp.route('/tags/<int:tag_id>')
def tags(tag_id):
    """
    标签
    ---
    tags:
        - blog
    description:
        - 标签详情
    parameters:
        - name: tag_id
          in: path
          description: 标签id
          required: true
          type: number
    responses:
        '200':
            description: 返回标签信息
        'default':
            description: Unexpected Error
    """
    # 标签页
    tag = Tag.query.get(tag_id)
    return render_template('tags.html', post_list=tag.post, tag=tag)


@bp.route('/search')
def search():
    """
    搜索框
    ---
    tags:
        - blog
    description:
        - 搜索
    parameters:
        - name: words
          in: query
          description: 关键字
          required: false
          type: string
    responses:
        '200':
            description: 返回搜索到的内容
        'default':
            description: Unexpected Error
    """
    words = request.args.get('words', '', type=str)
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.filter(Post.title.like('%'+words+'%')).\
        paginate(page=page, per_page=10, error_out=False)
    post_list = pagination.items
    return render_template('search.html', post_list=post_list, pagination=pagination, words=words)

Flask_Blog/app/blog/templates/archive.html
{% extends 'cate_list.html' %}

{% block title %}{{ date }}的文章归档 {% endblock title %}

{% block hero %}{% endblock hero %}

{% block breadcrumb %}
    <nav class="breadcrumb is-small" aria-label="breadcrumbs">
        <ul>
            <li><a href="/">首页</a></li>
            <li class="is-active"><a href="#" aria-current="page">{{ date }}的归档</a></li>
        </ul>
    </nav>
{% endblock breadcrumb %}

{% block pagination %}
    <nav class="pagination is-small" role="navigation" aria-label="pagination">
        {% if pagination.has_prev %}
            <a href="{{ url_for('blog.archive', date=date ) }}?page={{ pagination.prev_num }}" class="pagination-previous" title="This is the first page">Previous</a>
        {% endif %}
        {% if pagination.has_next %}
            <a href="{{ url_for('blog.archive', date=date) }}?page={{ pagination.next_num }}" class="pagination-next">Next page</a>
        {% endif %}

        <ul class="pagination-list">        
            {% for page in pagination.iter_pages() %}
                {% if page %} 
                    {% if page != pagination.page %}
                        <li>
                            <a href="{{ url_for('blog.archive', date=date) }}?page={{ page }}" class="pagination-link" aria-label="Page 1" aria-current="page">{{ page }}</a>
                        </li>
                    {% else %}
                        <li>
                            <a class="pagination-link is-current" aria-label="Page 1" aria-current="page">{{ page }}</a>
                        </li>
                    {% endif %}
                {% else %}
                    <span class=pagination-ellipsis>&hellip;</span>
                {% endif %}
                {% endfor %}
            </ul>
        </nav>
{% endblock pagination %}

Flask_Blog/app/blog/templates/base.html
<!DOCTYPE html>
<html lang="cn">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}首页{% endblock title %}</title>
    <link rel="stylesheet" href="{{ url_for('blog.static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('blog.static', filename='css/buefy.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('blog.static', filename='css/materialdesignicons.min.css') }}">

{#  避免浏览器报错 favicon.ico [HTTP/1.1 404 NOT FOUND 0ms]#}
{#  也可以准备一个图标放进 static/img 文件夹中，在调用#}
    <link rel="shortcut icon" href="#"/>

    {% block extra_head_style %}{% endblock extra_head_style %}
</head>

<body>
    <div id="app" style="height:100%;">
        <div class="container is-fluid1" style="height:100%; ">
            <div class="is-block" style="height:100%;">
                <!-- 导航 -->
                {% block navbar %}
                <template>
                    <b-navbar spaced shadow>
                        <template #brand>
                            <b-navbar-item>
                                <img src="{{ url_for('blog.static', filename='img/logo.png') }}" alt="FlaskBlog">
                            </b-navbar-item>
                        </template>
                        <template #start>
                            <b-navbar-item href="/">
                                首页
                            </b-navbar-item>
                            {% for cate in categorys %}
                            <b-navbar-item
                                    {% if cate.id == cate_id %}class="has-text-primary"{% endif %}
                                    href="{{ url_for('blog.cates', cate_id=cate.id) }}">
                                {{ cate.name }}
                            </b-navbar-item>
                            {% endfor %}
                        </template>

                        <template #end>
                            <b-navbar-item tag="div">
                                <!-- 判断用户是否已登录 -->
                                {% if g.user %}
                                <div class=" buttons">
                                    <!-- 获取用户信息 -->
                                    <a class="button is-primary">欢迎您 {{ g.user['username'] }}</a>
                                    <a class="button is-success" href="{{ url_for('auth.userinfo') }}">个人中心</a>
                                    <!-- 显示退出按钮 -->
                                    <a class="button is-danger" href="{{ url_for('auth.logout') }}">退出</a>
                                </div>
                                {% else %}
                                <!-- 用户未登录，显示登录注册按钮 -->
                                <div class="buttons">
                                    <a class="button is-primary" href="{{ url_for('auth.register') }}">
                                        <strong>Sign up</strong>
                                    </a>
                                    <a class="button is-light" href="{{ url_for('auth.login') }}">Log in</a>
                                </div>
                                {% endif %}
                            </b-navbar-item>
                        </template>
                    </b-navbar>
                </template>
                {% endblock navbar %}
                <!-- 导航 end -->

                {% block hero %}
                <section class="hero is-medium is-primary">
                    <div class="hero-body">
                        <p class="title">
                            Large hero
                        </p>
                        <p class="subtitle">
                            Large subtitle
                        </p>
                    </div>
                </section>
                {% endblock hero %}

                {% block main %}
                <div class="box is-marginless is-shadowless is-radiusless">

                    {% block box %}

                    <div class="columns is-multiline">
                        {% for post in post_list %}
                        <div class="column is-4-fullhd">
                            <div class="card">
                                <div class="card-image">
                                    <figure class="image is-4by3">
                                        <img src="{{ post.img }}"
                                            alt="Placeholder image">
                                    </figure>
                                </div>
                                <div class="card-content">
                                    <div class="media">
                                        <div class="media-content">
                                            <p class="title is-4">
                                                <a href="{{ url_for('blog.detail', cate_id=post.category.id, post_id=post.id) }}">
                                                    {{ post.title }}
                                                </a>
                                            </p>
                                        </div>
                                    </div>

                                    <div class="content">
                                        <p class=" has-text-grey is-size-7">
                                            {{ post.content[:32] }}
                                        </p>
                                        <time datetime="2016-1-1">11:09 PM - 1 Jan 2016</time>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>


                    <nav class="pagination is-small" role="navigation" aria-label="pagination">
                        {% if pagination.has_prev %}
                        <a href="{{ url_for('/') }}?page={{ pagination.prev_num }}" class="pagination-previous" title="This is the first page">Previous</a>
                        {% endif %}
                        {% if pagination.has_next %}
                        <a href="{{ url_for('/') }}?page={{ pagination.next_num }}" class="pagination-next">Next page</a>
                        {% endif %}

                        <ul class="pagination-list">
                            {% for page in pagination.iter_pages() %}
                                {% if page %}
                                    {% if page != pagination.page %}
                                    <li>
                                        <a href="{{ url_for('/') }}?page={{ page }}" class="pagination-link" aria-label="Page 1" aria-current="page">{{ page }}</a>
                                    </li>
                                    {% else %}
                                    <li>
                                        <a class="pagination-link is-current" aria-label="Page 1" aria-current="page">{{ page }}</a>
                                    </li>
                                    {% endif %}
                                {% else %}
                                    <span class=pagination-ellipsis>&hellip;</span>
                                {% endif %}
                            {% endfor %}

                        </ul>
                    </nav>

{#                    <nav class="pagination" role="navigation" aria-label="pagination">#}
{#                        <a class="pagination-previous is-disabled" title="This is the first page">Previous</a>#}
{#                        <a class="pagination-next">Next page</a>#}
{#                        <ul class="pagination-list">#}
{#                          <li>#}
{#                            <a class="pagination-link is-current" aria-label="Page 1" aria-current="page">1</a>#}
{#                          </li>#}
{#                          <li>#}
{#                            <a class="pagination-link" aria-label="Goto page 2">2</a>#}
{#                          </li>#}
{#                          <li>#}
{#                            <a class="pagination-link" aria-label="Goto page 3">3</a>#}
{#                          </li>#}
{#                        </ul>#}
{#                    </nav>#}
                    {% endblock box %}
                </div>
                {% endblock main %}



                {% block footer %}
                <div class="footer has-background-black-ter is-marginless">
                    <div class="has-text-centered has-text-grey-light">
                        © 2022 <a class="has-text-grey-light" href="http://www.lotdoc.cn/blog/topic/detail/6/">FlaskBlog博客实战</a> 版权所有 备案号：陕ICP备20005686号
                    </div>
                </div>
                {% endblock footer %}
            </div>

        </div>
    </div>

    <script src="{{ url_for('blog.static', filename='js/vue.js') }}"></script>
    <script src="{{ url_for('blog.static', filename='js/buefy.min.js') }}"></script>
    {% block extra_foot_script %}{% endblock extra_foot_script %}
    <script>
        var app = new Vue({
            el: '#app',
            data: {},
            methods: {}
        })
    </script>
    {% block vue_script %}{% endblock vue_script %}
</body>

</html>

Flask_Blog/app/blog/templates/cate_list.html
{% extends 'base.html' %}

{% block title %}{{ cate.name }}{% endblock title %}

{% block hero %}{% endblock hero %}

{% block box %}
<div class="columns">
    <div class="column is-9" style="border-right:solid 1px #eee ;">
        <div class="box is-shadowless has-background-light">
            {% block breadcrumb %}
            <nav class="breadcrumb is-small" aria-label="breadcrumbs">
                <ul>
                <li><a href="/">首页</a></li>
                <li class="is-active"><a href="#" aria-current="page">{{ cate.name }}</a></li>
                </ul>
            </nav>
            {% endblock breadcrumb %}
        </div>

        {% block cate_box %}
        {% for post in post_list %}
            <div class="pl-2">
                <h1 class="is-size-4">
                    <a href="{{ url_for('blog.detail', cate_id=post.category.id, post_id=post.id) }}">{{ post.title }}</a>
                </h1>
                <p class="has-text-grey-light is-size-6 mt-1">
                    <span class="icon"><i class="mdi mdi-clipboard-text-clock-outline"></i></span>{{ post.add_date }}
                    <span class="icon"><i class="mdi mdi-shape-outline"></i></span>{{ post.category.name }}
                    <span class="icon"><i class="mdi mdi-tag-heart-outline"></i></span>{{ post.tags|join(',') }}
                </p>
                <div class="has-text-grey mt-1">{{ post.desc }}</div>
            </div>
            <div class=" dropdown-divider mb-3"></div>
        {% endfor %}
        {% block pagination %}
        <nav class="pagination is-small" role="navigation" aria-label="pagination">
            {% if pagination.has_prev %}
            <a href="{{ url_for('blog.cates', cate_id=cate.id ) }}?page={{ pagination.prev_num }}" class="pagination-previous" title="This is the first page">Previous</a>
            {% endif %}
            {% if pagination.has_next %}
            <a href="{{ url_for('blog.cates', cate_id=cate.id) }}?page={{ pagination.next_num }}" class="pagination-next">Next page</a>
            {% endif %}

            <ul class="pagination-list">        
                {% for page in pagination.iter_pages() %}
                    {% if page %} 
                        {% if page != pagination.page %}
                        <li>
                            <a href="{{ url_for('blog.cates', cate_id=cate.id) }}?page={{ page }}" class="pagination-link" aria-label="Page 1" aria-current="page">{{ page }}</a>
                        </li>
                        {% else %}
                        <li>
                            <a class="pagination-link is-current" aria-label="Page 1" aria-current="page">{{ page }}</a>
                        </li>
                        {% endif %}
                    {% else %}
                        <span class=pagination-ellipsis>&hellip;</span>
                    {% endif %}
                {% endfor %}

            </ul>
        </nav>
            {% endblock pagination %}
        {% endblock cate_box %}
    </div>
    <div class="column">
        <div class="box is-shadowless" style="border:solid 1px #eee ;">
            <h1 class="is-size-6 icon-text">
                <span class="icon"><i class="mdi mdi-search-web"></i></span>
                搜索
            </h1>
            <div class=" dropdown-divider"></div>
            <form action="{{ url_for('blog.search') }}" method="get">
                <div class="field has-addons">
                    <div class="control">
                    <input class="input" type="search" value="{{ words }}" name="words" placeholder="请输入关键字">
                    </div>
                    <div class="control">
                    <input type="submit" value="Search" class="button is-info">
                    </div>
                </div>
            </form>
        </div>
        <div class="box is-shadowless" style="border:solid 1px #eee ;">
            <h1 class="is-size-6 icon-text">
                <span class="icon"><i class="mdi mdi-calendar-month-outline"></i></span>
                最新文章
            </h1>
            <div class=" dropdown-divider"></div>
            <ul>
                {% for post in new_posts %}
                <li class="pl-2">
                    <span class=" has-text-grey-light">{{ loop.index }}.</span>
                    <a href="{{ url_for('blog.detail', cate_id=post.category.id, post_id=post.id) }}">{{ post.title }}</a>
                </li>
                <div class="dropdown-divider"></div>
                {% endfor %}
            </ul>
        </div>
        <div class="box is-shadowless" style="border:solid 1px #eee ;">
            <h1 class="is-size-6 icon-text">
                <span class="icon"><i class="mdi mdi-calendar-month-outline"></i></span>
                归档
            </h1>
            <div class=" dropdown-divider"></div>
            <ul>
                {% for date in dates %}
                <li class="pl-2"><a href="{{ url_for('blog.archive', date=date) }}">{{ date }}</a></li>
                <div class="dropdown-divider"></div>
                {% endfor %}
            </ul>
        </div>

        <div class="box is-shadowless" style="border:solid 1px #eee ;">
            <h1 class="is-size-6 icon-text">
                <span class="icon"><i class="mdi mdi-tag-multiple-outline"></i></span>
                标签
            </h1>
            <div class=" dropdown-divider"></div>
                <div class="tags">
                    {% for tag in tags %}
                    <a class="tag {{ tag.style|random() }}" href="{{ url_for('blog.tags', tag_id=tag.id) }}">{{ tag.name }}</a>
                    {% endfor %}
                </div>
        </div>
    </div>
</div>
{% endblock box %}

Flask_Blog/app/blog/templates/detail.html
{% extends 'cate_list.html' %}

{% block title %}
    {{ post.title }}
{% endblock title %}

{% block breadcrumb %}
    <nav class="breadcrumb is-small" aria-label="breadcrumbs">
        <ul>
            <li><a href="/">首页</a></li>
            <li><a href="{{ url_for('blog.cates', cate_id=cate.id) }}">{{ cate.name }}</a></li>
            <li class="is-active"><a href="#" aria-current="page">{{ post.title }}</a></li>
        </ul>
    </nav>
{% endblock breadcrumb %}

{% block cate_box %}
<div class="pl-2">
    <h1 class="is-size-3">
        {{ post.title }}
    </h1>
    <p class="has-text-grey-light is-size-6 mt-1">
        <span class="icon"><i class="mdi mdi-clipboard-text-clock-outline"></i></span>{{ post.add_date }}
        <span class="icon"><i class="mdi mdi-shape-outline"></i></span>{{ post.category.name }}
        <span class="icon"><i class="mdi mdi-tag-heart-outline"></i></span>{{ tag_list|join(' ') }}
    </p>
    <div class="content has-text-grey mt-1">{{ post.content|safe }}</div>
</div>

<hr>
<div class="level">
    <div class="level-left">
        {% if prev_post %}
            上一篇：<a href="{{ url_for('blog.detail', cate_id=prev_post.category.id, post_id=prev_post.id) }}">{{ prev_post.title }}</a>
        {% endif %}
    </div>
    <div class="level-right">
        {% if next_post %}
            下一篇：<a href="{{ url_for('blog.detail', cate_id=next_post.category.id, post_id=next_post.id) }}">{{ next_post.title }}</a>
        {% endif %}
    </div>
</div>
{% endblock cate_box %}

Flask_Blog/app/blog/templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>hello</title>
</head>
<body>
  <p>hello</p>
</body>
</html>

Flask_Blog/app/blog/templates/index.html
{% extends 'base.html' %}

Flask_Blog/app/blog/templates/search.html
{% extends 'cate_list.html' %}

{% block title %}{{ words }}的搜索结果 {% endblock title %}

{% block hero %}{% endblock hero %}

{% block breadcrumb %}
    <nav class="breadcrumb is-small" aria-label="breadcrumbs">
        <ul>
            <li><a href="/">首页</a></li>
            <li class="is-active"><a href="#" aria-current="page">{{ words }}</a></li>
        </ul>
    </nav>
{% endblock breadcrumb %}

{% block pagination %}
    <nav class="pagination is-small" role="navigation" aria-label="pagination">
        {% if pagination.has_prev %}
            <a href="{{ url_for('blog.search') }}?page={{ pagination.prev_num }}&words={{ words }}" class="pagination-previous" title="This is the first page">Previous</a>
        {% endif %}
        {% if pagination.has_next %}
            <a href="{{ url_for('blog.search') }}?page={{ pagination.next_num }}&words={{ words }}" class="pagination-next">Next page</a>
        {% endif %}

        <ul class="pagination-list">        
            {% for page in pagination.iter_pages() %}
                {% if page %} 
                    {% if page != pagination.page %}
                        <li>
                            <a href="{{ url_for('blog.search') }}?page={{ page }}&words={{ words }}" class="pagination-link" aria-label="Page 1" aria-current="page">{{ page }}</a>
                        </li>
                    {% else %}
                        <li>
                            <a class="pagination-link is-current" aria-label="Page 1" aria-current="page">{{ page }}</a>
                        </li>
                    {% endif %}
                {% else %}
                    <span class=pagination-ellipsis>&hellip;</span>
                {% endif %}
                {% endfor %}
            </ul>
        </nav>
{% endblock pagination %}

Flask_Blog/app/blog/templates/tags.html
{% extends 'cate_list.html' %}

{% block title %}{{ tag.name }} {% endblock title %}

{% block hero %}{% endblock hero %}

{% block breadcrumb %}
    <nav class="breadcrumb is-small" aria-label="breadcrumbs">
        <ul>
            <li><a href="/">首页</a></li>
            <li class="is-active"><a href="#" aria-current="page">{{ tag.name }}</a></li>
        </ul>
    </nav>
{% endblock breadcrumb %}

{% block pagination %}
{% endblock pagination %}